#####
# Database
#####
database:
  url: "jdbc:mysql://localhost:3306/openmc"
  username: user
  password: ""

features:
  analytics: true
  transactions: true

#####
# Param√®tres pour un environnement de production
#####
homepage: "https://openmc.fr/"
discord: "https://discord.gg/aywen/"
blog: "https://blog.openmc.fr/"